// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCip4X3-xB8ZJ8-v22GNYuJLAJuE5tylRk',
    appId: '1:27086551424:web:c79e7bcfeb5e0e45792965',
    messagingSenderId: '27086551424',
    projectId: 'hangman-userbase',
    authDomain: 'hangman-userbase.firebaseapp.com',
    storageBucket: 'hangman-userbase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGmw2HvRYtA54X2UdN8h4s0Fr3zbMucNE',
    appId: '1:27086551424:android:6a883d148ba2f200792965',
    messagingSenderId: '27086551424',
    projectId: 'hangman-userbase',
    storageBucket: 'hangman-userbase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAr9yG0J-Ocb0EImTnU1QWD1psDLXC9go',
    appId: '1:27086551424:ios:e472707f2f3735c9792965',
    messagingSenderId: '27086551424',
    projectId: 'hangman-userbase',
    storageBucket: 'hangman-userbase.firebasestorage.app',
    iosBundleId: 'com.example.hangmangame',
  );
}
